version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      - films
    expose:
      - "3000"
  films:
    build:
      context: ./films
    environment:
      - MONGO_URL=mongodb://mongo:27017/filmsdb
    depends_on:
      - mongo
    expose:
      - "3000"
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/srv/www/static:ro
    depends_on:
      - web
      - films
