version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - films
  films:
    build: ./films
    environment:
      - MONGO_URL=mongodb://mongo:27017/filmsdb
    ports:
      - "3001:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/srv/www/static:ro
    depends_on:
      - web
      - films
